server:
  port: 8080

spring:
  application:
    name: wpct
  datasource:
    url: jdbc:mysql://47.98.120.130:3306/wpct2?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: wpct2
    password: 123456

  redis:
    host: 47.98.120.130
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.tbxx.wpct.entity
  mapper-locations: classpath:/mapper/*.xml


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

